# Generated by Django 5.2.1 on 2025-06-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=255, unique=True)),
                ('call_time', models.DateTimeField()),
                ('call_end_time', models.DateTimeField()),
                ('duration_seconds', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Call Data',
                'verbose_name_plural': 'Call Data',
                'ordering': ['-call_time'],
            },
        ),
    ]
